# https://github.com/docker-library/wordpress
# https://github.com/docker-library/wordpress/blob/master/latest/php8.2/fpm/Dockerfile
# https://conetix.com.au/blog/what-is-a-dockerfile/
# https://www.wordpressdocker.com/

# Subjectte Dockerfile için Alpine veya Debian kullanılması önerilmektedir, bu yüzden kararlı olan bir önceki sürüm tercih edilmiştir.
# FROM debian:buster

# WORKDIR /var/www/html

# # WordPress'i çalıştırmak için gerekli temel seviye bileşenler. 
# RUN apt-get update && apt-get install -y \
# 		php8.2 \
# 		php-mysqli \
# 		php-fpm \
# 		php-cgi

# COPY ./conf/wp-config.php /var/www/html/wp-config.php

# EXPOSE 9000

# CMD [ "php-fpm" ]